// generated by run_match.py -- data for results_viewer.html
window.MATCH_HISTORY = [
 {
  "date": "2026-07-06T22:45:00",
  "label_a": "bugfixes",
  "label_b": "baseline-424b0e0",
  "engine_a": "build\\ChessUCI.exe",
  "engine_b": "testbed\\baselines\\ChessUCI-424b0e0-20260706.exe",
  "control": "200 ms/move",
  "games": 20,
  "wins": 10,
  "losses": 1,
  "draws": 9,
  "score": 0.725,
  "elo": 168.4,
  "margin": 119.8,
  "los": 0.9966,
  "incidents": 1,
  "duration_s": 174,
  "out_dir": "testbed\\results\\bugfix_sanity"
 },
 {
  "date": "2026-07-07T00:48:34",
  "label_a": "bugfixes",
  "label_b": "baseline",
  "engine_a": "build\\ChessUCI.exe",
  "engine_b": "testbed\\baselines\\ChessUCI-424b0e0-20260706.exe",
  "control": "1000 ms/move",
  "games": 100,
  "wins": 60,
  "losses": 11,
  "draws": 29,
  "score": 0.745,
  "elo": 186.2,
  "margin": 64.0,
  "los": 1.0,
  "incidents": 9,
  "duration_s": 4477,
  "out_dir": "C:\\Users\\clanc\\VSCode\\chess_ai\\testbed\\results\\match_20260706_233357"
 }
];
